- name: NGINX | Remove Apache
  apt: pkg=apache2 state=absent purge=yes

- name: NGINX | Install NGINX
  apt: pkg=nginx state=installed

- name: NGINX | Copy Host Config
  template: src={{ (item.config is defined) | ternary(item.config, './templates/site.conf.j2') }} src=./templates/site.conf.j2 dest=/etc/nginx/sites-available/{{ item.name }}.conf
  with_items: "{{domains}}"

- name: NGINX | Copy Server Config
  template: src=./templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: NGINX | Remove Default Configuration
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: NGINX | Activate Hosts
  file: src=/etc/nginx/sites-available/{{ item.name }}.conf dest=/etc/nginx/sites-enabled/{{ item.name }}.conf state=link
  with_items: "{{domains}}"
  notify: restart nginx
