---
- name: PHP-FPM | Install PHP7.1-FPM
  apt: pkg=php7.1-fpm state=installed

- name: PHP-FPM | Install Primary Configuration File
  template: src=../templates/php-fpm.conf.j2 dest=/etc/php/7.1/fpm/php-fpm.conf

- name: PHP-FPM | Install WWW Pool Configuration File
  template: src=../templates/php-fpm_pool.conf.j2 dest=/etc/php/7.1/fpm/pool.d/www.conf
  notify: restart php7.1-fpm

- name: PHP-FPM | Install Custom PHP.ini Configurations for FPM PHP
  ini_file: dest=/etc/php/7.1/fpm/php.ini
            section=PHP
            option={{ item.option }}
            value={{ item.value }}
            backup=yes
  with_items: "{{php_configs}}"

